### ISSUE TITLE
TypeError: githubEvent is not a function

### ISSUE THREAD

**Issue by Gr8z** [calibreapp/image-actions#73]
Just started getting this a few hours ago, no config changes were done.

```
(node:1) UnhandledPromiseRejectionWarning: TypeError: githubEvent is not a function
    at main (/usr/local/src/image-actions/entrypoint.js:26:25)
    at Object.<anonymous> (/usr/local/src/image-actions/entrypoint.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by benschwarz** [comment]
Thanks for reporting @Gr8z. Fix incoming…

**Comment by benschwarz** [comment]
@Gr8z I've landed a fix. Can you verify it's working again?

**Comment by Gr8z** [comment]
Just tested again, I am getting the same error @benschwarz

**Comment by benschwarz** [comment]
I've confirmed it's working on an internal PR. Could you try closing/re-opening your PR, or creating a new one and sharing the log output? 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/924/93172947-24db3e00-f76f-11ea-8195-76ae2e9dc0c6.png">

**Comment by Gr8z** [comment]
@benschwarz the checks pass even though there is an error in one of those steps. If you expand "Compress Images", you will see the error.

**Comment by Gr8z** [comment]
Oh looks like the problem is gone when I opened a new PR. Thanks for the fast fix.

**Comment by benschwarz** [comment]
No prob! Sorry I realised a broken entry point 😅
